### ISSUE TITLE
Add a new condition UpgradeInProgress 

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#106]
**What would you like to be added**:
When the upgrade is in progress, the condition "UpgradeInProgress" should be true

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by nayihz** [comment]
`upgrade` means lws template hash changed, right?

**Comment by kerthcet** [comment]
Then what about the `LeaderWorkerSetProgressing`, the difference is `LeaderWorkerSetProgressing` includes `UpgradeInProgress`?

**Comment by liurupeng** [comment]
@kerthcet correct, this condition would show the lws is in update status? wdyt

**Comment by kerthcet** [comment]
Personally I don't like the idea about we have two status type `Progressing` and `UpgradeInProgress` which represents the same thing, that's say when rolling update, Progressing and UpgradeInProgress both true. My suggestion is we can reuse the `Progressing` type but have another reason like `GroupsRollingUpdate`

**Comment by Edwinhr716** [comment]
So only one of `GroupsRollingUpdate` and `Progressing` will be true at the same time?

**Comment by kerthcet** [comment]
Sorry, one question about the motivation, why we need this? I didn't see similar field in deployment/statefulset. And once we delete a leaderSts/leaderPod, how can we know we're rolling update or just normal processing? Maybe `GroupsAreProgressing` is enough.

**Comment by kerthcet** [comment]
Make sense to help calculating the rolling update duration.

**Comment by kerthcet** [comment]
> So only one of GroupsRollingUpdate and Progressing will be true at the same time?

What I mean is **Progressing should include the rolling update from the semantics**, so

When creating or other actions
```
  - lastTransitionTime: "2024-04-16T16:13:01Z"
    message: Replicas are progressing
    reason: GroupsAreProgressing
    status: "True"
    type: Progressing
```

When rolling update
```
  - lastTransitionTime: "2024-04-16T16:13:01Z"
    message: Replicas are rolling update
    reason: GroupsRollingUpdate
    status: "True"
    type: Progressing
```

when completes (create/update):
```
  - lastTransitionTime: "2024-04-16T16:13:01Z"
    message: Replicas have successfully progressed
    reason: GroupsProgressed
    status: "True"
    type: Progressing
```

Open for suggestions. cc @ahg-g @liurupeng 

I guess this doesn't break the compatibility, we didn't change the meaning, but we do change the condition status of the completed condition.

**Comment by ahg-g** [comment]
I think we can add UpdateInProgress and UpdateComplete as two mutually exclusive conditions. 

At steady state, the two conditions that should exist are "Available" and "UpdateComplete" if an update was ever triggered.

Any other time, I think we could have Progressing and UpdateInProgress conditions set. `Progressing` tracks if there are any replicas that are not ready yet (not created, or created and not ready). UpdateInProgress is set only when there is still at least one replica not yet updated.

**Comment by kerthcet** [comment]
If we can use one condition with different reasons to distinguish the stages, I think it's more straightforward. Or we have other reasons? 

And if one workerSts/leaderPod is deleted, we can't simply tell whether it's under creation or rolling update, which means hard to decide whether we should set it to `Progressing` or `UpdateInProgress`. However, with one condition, once rolling update starts, it will never enter into `Progressing` stage. My two cents.

**Comment by liurupeng** [comment]
I think we could start with adding updateInProgress at first, which the definition is "UpgradeInProgress is true when a rolling update started and has been completed" (including maxSurge), thoughts?
