### ISSUE TITLE
Change API version to v1alpha1

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/lws#12]
The current API indicates v1, and it means that we can not apply breaking changes to the API, but I think we should start from the alpha version API so that we can improve the API based on some feedback.

https://github.com/kubernetes-sigs/lws/blob/9af20f61ba6d4e4ebd97b43bfa6ffca5aa618743/api/leaderworkerset/v1/groupversion_info.go#L28-L29

@ahg-g @liurupeng WDYT?

**Comment by kerthcet** [comment]
+1

**Comment by ahg-g** [comment]
That is indeed the practice, but for the most part once people start using it, it becomes "GA" and it is hard to move them off of it.

If we believe that the initial API is simple enough to allow improving it via addition only, then I think it is ok to start with v1 from the get go.

What do you think?

**Comment by kerthcet** [comment]
Fair enough, I think we can leave this question to the first release, then we'll get more feedbacks.

**Comment by tenzen-y** [comment]
> That is indeed the practice, but for the most part once people start using it, it becomes "GA" and it is hard to move them off of it.
> 
> If we believe that the initial API is simple enough to allow improving it via addition only, then I think it is ok to start with v1 from the get go.
> 
> What do you think?

I'm ok with starting v1, but my main concern is backward compatibility.
When we need to break backward compatibility, we need to cut a new v2 API and provide a conversion webhook.

I believe that we want to avoid such a case as much as possible since those would bring high maintenance costs :(
@ahg-g @kerthcet WDYT?

**Comment by tenzen-y** [comment]
> I think the maintenance costs will exist anyway, even if we release in v1alpha1, customers will use it and we will have to provide backward compatibility for sometime anyway.

That sounds reasonable. I'm ok with keeping v1.
