### ISSUE TITLE
Flaky test for "multiple rolling update with maxSurge set"

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#134]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kerthcet** [comment]
/assign

I'll take my job.
