### ISSUE TITLE
Add a startup policy API to indicate that the workers are created only after the leader is ready

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/lws#135]
**What would you like to be added**:

Startup policy API to delay creating the workers sts until the leader is ready

**Why is this needed**:
some frameworks require the leader to start (like ray head) before the workers are started so they can connect to it.

**Comment by nayihz** [comment]
I'd like to have a try. Here are some thoughts about this feature.
1. First, let's define this startup policy as `WaitForLeaderReady`. 
2. lws controller will set worker sts `replicas=0` before all leader sts pod are ready. 
3. Pod controller will watch the leader sts status(`status.readyReplicas == status.replicas (or spec.replicas)`) and scale worker sts replicas to actual value after all leader sts pod are ready.

**Comment by kerthcet** [comment]
Make sense.

**Comment by kerthcet** [comment]
@nayihz I think it worth a simple KEP since we're adding a new API which also helps to organize the logics in advance.

**Comment by nayihz** [comment]
> @nayihz I think it worth a simple KEP since we're adding a new API which also helps to organize the logics in advance.

OK.
/assign

**Comment by liurupeng** [comment]
this is nice! thanks @ahg-g
