### ISSUE TITLE
spec.rolloutStrategy should be a non-required field

### ISSUE THREAD

**Issue by gujingit** [kubernetes-sigs/lws#147]
**What would you like to be added**:
spec.rolloutStrategy is set to a non-required field

**Why is this needed**:
`spec.rolloutStrategy` is a required field in lws crd now, and it is filled in the mutating webhook.  `spec.rolloutStrategy` should not be required.  If it's null, it alse should be filled in the controller instead of the webhook, just like deployment resource.

```
// DeploymentStrategy describes how to replace existing pods with new ones.
type DeploymentStrategy struct {
	// Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
	// +optional
	Type DeploymentStrategyType `json:"type,omitempty" protobuf:"bytes,1,opt,name=type,casttype=DeploymentStrategyType"`

	// Rolling update config params. Present only if DeploymentStrategyType =
	// RollingUpdate.
	//---
	// TODO: Update this to follow our convention for oneOf, whatever we decide it
	// to be.
	// +optional
	RollingUpdate *RollingUpdateDeployment `json:"rollingUpdate,omitempty" protobuf:"bytes,2,opt,name=rollingUpdate"`
}
```

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
This follows https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required, especially `Therefore, we ask that pointers always be used with optional fields that do not have a built-in nil value.`. But seems a little weird for users **it's required, but can be empty**. @nayihz also talked with me before. @ahg-g do you agree with this change?

**Comment by ahg-g** [comment]
yeah, that sounds good to me.

**Comment by nayihz** [comment]
`spec.leaderWorkerTemplate.restartPolicy` also have same issue.
ref: https://github.com/kubernetes-sigs/lws/pull/91#discussion_r1562266155

**Comment by kerthcet** [comment]
Would you like to push this forward? @gujingit Hope to include this in v0.3.0
