### ISSUE TITLE
Create ClusterIP service for leader Pods

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#149]
**What would you like to be added**:

LWS is a leader-worker architecture, leader may play more roles like in ray, the header(leader in lws) will accept job submission requests, so we can make it more integrated to create a clusterIP service which can load-balancing the traffic to leaderPods of each replicas. Just like kserve has rayDeployment which will also create services. 

We have a headless service right now but it acts more like a discovery mechanism especially with the support of `PublishNotReadyAddresses`.

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Should be implemented at a high level.

/close

**Comment by panpan0000** [comment]
https://github.com/kubernetes-sigs/lws/blob/80af0086/keps/173-headless-service-per-replica/README.md
this one ?
