### ISSUE TITLE
Support not to create headless service

### ISSUE THREAD

**Issue by gujingit** [kubernetes-sigs/lws#164]
**What would you like to be added**:
Add params in crd to allow configure headless service. The headless service should be configurable because user need to update headless service (e.g. update service selector) or use other service (e.g. NodePort, LoadBalancer) in some cases. 

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Headless service can be used to establish connections before providing service. With `publishNotReadyAddresses` enabled by default, I think it's not quite fit for business traffic actually.

**Comment by liurupeng** [comment]
Is there a use case that needs to make the headless service to be configurable?

**Comment by gujingit** [comment]
> Headless service can be used to establish connections before providing service. With `publishNotReadyAddresses` enabled by default, I think it's not quite fit for business traffic actually.

Yes, you're right. We will create a new service for business traffic.
