### ISSUE TITLE
No need to create worker statefulsets when size=1

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#189]
**What would you like to be added**:

Once we set the size = 1, if we have 10 replicas, we'll have 10 0-replica statefulsets, there's no need to create these statefulsets.

**Why is this needed**:

When using lws as single-host workload(size=1), this leads to confusion and additional computations.

cc @ahg-g @liurupeng 

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by ahg-g** [comment]
sounds good to me
