### ISSUE TITLE
Increase number of replica of the LWS controller to be deployed to cluster for better failover

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#19]
Right now, we only deploy one replica of LWS controller in the cluster. When the controller is down, the reconciliation will not work and need to wait for it becoming ready again. We need to increase replica count and enabled leader election

**Comment by liurupeng** [comment]
@Edwinhr716

**Comment by ahg-g** [comment]
Did we address this one?

**Comment by liurupeng** [comment]
nope, not yet
