### ISSUE TITLE
Change default of restart policy to RecreateGroupOnPodRestart

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/lws#204]
**What would you like to be added**:

Change default of restart policy to RecreateGroupOnPodRestart.

**Why is this needed**:

It will be the most commonly used restart policy.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
We should change the name as well, or `Default` policy but not default, and default is somehow unclear, default for what? Maybe `None`, which means the lws will not do anything, it's all the pod behavior.

**Comment by ahg-g** [comment]
hmm, unfortunately we can't remove it, but perhaps we can add a `None` value and in the webhook we re-write anything that sets Default to None.

**Comment by kerthcet** [comment]
For backwards compatibility? We can mark it as deprecated and remove that in the future.

**Comment by ahg-g** [comment]
Sounds good, do you have time to do this?

**Comment by kerthcet** [comment]
on the way.
