### ISSUE TITLE
Support to install lws at user specified namespace

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#215]
**What would you like to be added**:

Hope to install lws at a configurable namespace rather than the hardcode lws-system. 

Here's a code snippet  we need to care about: https://github.com/kubernetes-sigs/lws/blob/main/pkg/cert/cert.go#L27

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by googs1025** [comment]
/assign 
I understand that we need to provide a configurable namespace right?

**Comment by liurupeng** [comment]
+1 to the proposal

**Comment by googs1025** [comment]
https://github.com/kubernetes-sigs/lws/issues/170 

Is it consistent with this issue?

**Comment by kerthcet** [comment]
Yes, this should be part of the CC, would you like to take it over @googs1025
