### ISSUE TITLE
Flaky test "Can perform a rolling update with subgroupsize and MaxSurge set"

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/lws#222]
Log: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_lws/217/pull-lws-test-e2e-main-1-31/1834756867335655424

https://github.com/kubernetes-sigs/lws/pull/217#issuecomment-2350768092

/assign @Edwinhr716

**Comment by Edwinhr716** [comment]
Test follows the same checks and format as the other rollingUpdate + MaxSurge tests. The same line that fails https://github.com/kubernetes-sigs/lws/blob/main/test/e2e/e2e_test.go#L184, works on other MaxSurge tests https://github.com/kubernetes-sigs/lws/blob/main/test/e2e/e2e_test.go#L138. The test itself checks if MaxSurge still works if subgroupsize is set. The only thing that subGroupSize sets is labels, so there's no reason for it to fail in this case but succeed in others, which means it is a race condition. 

Not sure what the solution would be here which would not make it different from other maxSurge tests.

**Comment by Edwinhr716** [comment]
Test isn't failing anymore, wdyt of closing the issue? @ahg-g
