### ISSUE TITLE
Replicas restart during rolling upgrade will not use the original worker pod spec

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#238]
**What happened**:
When lws is in rolling update, any replicas that are not updated yet, but restarted due to failure handling, the worker statefulset will be recreated with updated lws worker template. The expected behavior should be recreated with the previous worker template
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ahg-g** [comment]
The solution is https://github.com/kubernetes-sigs/lws/issues/239
