### ISSUE TITLE
When rollout new controller version, it should not trigger a rolling update

### ISSUE THREAD

**Issue by liurupeng** [kubernetes-sigs/lws#240]
**What happened**:
In the rolling update triggering logic, we should store the template somewhere else, and only compare the fields with the original one, and check if these fields are updated, then decides to trigger a rolling update. This will mitigate the issue when we added a API field, it will not trigger rolling update when rolling out new controller version
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ahg-g** [comment]
For the short term, lets patch the current release with a special fix for the new field we added, the NetworkConfig.

Basically if the NetworkConfig is set to the default values, set it to nil in the controller when calculating the hash, this should avoid changing the hash value when the new controller is rolled out.

**Comment by liurupeng** [comment]
yep, this could be a short term fix

**Comment by Edwinhr716** [comment]
For the short term fix, don't we already exclude NetworkConfig if it is nil https://github.com/kubernetes-sigs/lws/blob/main/pkg/utils/utils.go#L44? @ahg-g

**Comment by ahg-g** [comment]
The issue is that the NetworkConfig will not be nil since it will be defaulted, which means the hash for an existing deployment will be different from the one stored as an annotation and generated previously by the older operator version.

**Comment by Edwinhr716** [comment]
I thought it isn't defaulted when upgrading the LWS controller https://github.com/kubernetes-sigs/lws/pull/197#discussion_r1720806787, and that's why we added the nil check?

**Comment by ahg-g** [comment]
It is getting defaulted: https://github.com/kubernetes-sigs/lws/blob/0b8c0948dfb83f1cac26b488e9f85060d9553e10/pkg/webhooks/leaderworkerset_webhook.go#L75

But can you test that on a real cluster?

**Comment by Edwinhr716** [comment]
I tested upgrading from 0.2.0 to 0.4.1 and the upgrade did not trigger an upgrade of the statefulSets (so the template hash was not updated)

**Comment by ahg-g** [comment]
Check if the NetworkConfig get defaulted, if not, try to tigger an update on LWS that doesn't trigger a rolling update to trigger calling the defaulting function.

**Comment by Edwinhr716** [comment]
Upgraded from 0.2.0 to 0.4.1. NetworkConfig does not get defaulted. Updated LWS object by removing a metadata label to trigger defaulting option, NetworkConfig gets defaulted and rollingUpdate is triggered.

**Comment by ahg-g** [comment]
This will be addressed via https://github.com/kubernetes-sigs/lws/issues/239
