### ISSUE TITLE
Adding Helm Chart for lws

### ISSUE THREAD

**Issue by wqlparallel** [kubernetes-sigs/lws#260]
**What would you like to be added**:
Helm chart is now a normal artifact, widely used in CI/CD systems or displayed in application market, it seems charming if we can support this besides kustomize.  I am interested in contributing a Helm chart.

**Why is this needed**:

- A standard artifact to end-users.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by wqlparallel** [comment]
hi @Edwinhr716, just checking in-would it be okay if i start working on a Helm chart for lws?

**Comment by Edwinhr716** [comment]
Yes, sounds good to me. cc @ahg-g @liurupeng

**Comment by kerthcet** [comment]
Manifest is fairly enough to me, I would defer this unless users ask for support. Just because this adds maintenance cost to us. 

For example, we add lws manifest here  https://github.com/InftyAI/llmaz/tree/main/chart/templates/lws.

**Comment by cheyang** [comment]
> Manifest is fairly enough to me, I would defer this unless users ask for support. Just because this adds maintenance cost to us.
> 
> For example, we add lws manifest here https://github.com/InftyAI/llmaz/tree/main/chart/templates/lws.

Hi @kerthcet ,
We aim to provide Helm capabilities for `lws` in the public cloud, specifically for use in application markets where installations are managed via Helm charts. 

We will maintain consistency with the upstream version and intend to support both cloud and upstream deployments. This approach ensures that any updates or improvements are synchronized across upstream and ours.

**Comment by slin1237** [comment]
helm chart support would be useful

**Comment by kerthcet** [comment]
> We aim to provide Helm capabilities for lws in the public cloud, specifically for use in application markets where installations are managed via Helm charts.

Thanks, that's the feedbacks we're waiting for. Make sense then.
