### ISSUE TITLE
two lws-controller-manager instance？

### ISSUE THREAD

**Issue by ltm920716** [kubernetes-sigs/lws#264]
**What happened**:
I get two lws-controller-manager instance，I am not sure is that right？

**What you expected to happen**:
one lws-controller-manager instance？ and the instance should be start on master node，not worker node？

**How to reproduce it (as minimally and precisely as possible)**:
```
VERSION=v0.4.2
kubectl apply --server-side -f https://github.com/kubernetes-sigs/lws/releases/download/$VERSION/manifests.yaml
kc get pod -n lws-system
```
![1732179711447](https://github.com/user-attachments/assets/a12a8b94-2241-4b93-bfc9-494ea2244136)

**Anything else we need to know?**:
no

**Environment**:

- Kubernetes version (use `kubectl version`):
Client Version: v1.28.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.15

- LWS version (use `git describe --tags --dirty --always`):
VERSION=v0.4.2

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- Kernel (e.g. `uname -a`):
Linux k8s-master1 5.15.0-125-generic #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by Edwinhr716** [comment]
Check #19. On versions 0.4.0 and later two replicas of the LWS controller are deployed https://github.com/kubernetes-sigs/lws/blob/main/config/manager/manager.yaml#L31

**Comment by ltm920716** [comment]
ok，thanks！
