### ISSUE TITLE
Question about Commit Deployment in Specified Namespace

### ISSUE THREAD

**Issue by wqlparallel** [kubernetes-sigs/lws#276]
I've noticed that the [commit deployed in the specified namespace](https://github.com/kubernetes-sigs/lws/commit/1fe278e6470862113c743c67b53568cc7ae98d09) hasn’t been merged into the release version yet. Is there a particular reason for this delay or any considerations we should be aware of?

**Comment by kannon92** [comment]
Typically the maintainers decide when a release is necessary. I don’t think there are any concerns with this functionality.

**Comment by kannon92** [comment]
https://github.com/kubernetes-sigs/lws/issues/221

That feature you want is called out for the next release. I think they have 1 more feature that they want to put into 0.5.

**Comment by ahg-g** [comment]
This is planned for [v0.5.0](https://github.com/kubernetes-sigs/lws/issues/221), which is planned for late January.
