### ISSUE TITLE
Leader is killed twice during update when the restart policy is RecreateGroupOnPodRestart

### ISSUE THREAD

**Issue by xgchena** [kubernetes-sigs/lws#291]
**What happened**:

When the restart policy is RecreateGroupOnPodRestart, the leader restarts twice during update.

**What you expected to happen**:

The leader should only restart once to take the update.

**How to reproduce it (as minimally and precisely as possible)**:

Steps to reproduce:
1. Deploy a lws app with restart policy RecreateGroupOnPodRestart, e.g. [the vllm example](https://github.com/kubernetes-sigs/lws/blob/v0.3.0/docs/examples/vllm/lws.yaml).
2. When the app is up and running, make a change to the lws manifest (e.g. add a dummy env var to both leader and worker template), then apply the new manifest
3. Monitor the pods status change,
    1. Leader: Terminating, Worker: Running <= Leader restarts to take the change
    2. Leader: Running, Worker: Terminating <= Leader updates the Worker StatefulSet which in turn restarts the Worker to take the change
    3. Leader: Terminating, Worker: Running <= Worker restart caused Leader restart, which is unexpected
    4. Leader: Running, Worker: Running

**Anything else we need to know?**:

The problem seems [PodReconciler.handleRestartPolicy](https://github.com/kubernetes-sigs/lws/blob/v0.3.0/pkg/controllers/pod_controller.go#L181) blindly restarts the leader when a worker is killed. 

An additional check before the Delete statement should fix the issue: if the leader is already using the new template, but worker is not, It implies leader updating worker StatefulSet, in this case treat the leader as "deleted" and no need to send deletion request again.

**Environment**:

- Kubernetes version (use `kubectl version`): v1.31.3
- LWS version (use `git describe --tags --dirty --always`): v0.3.0-8-ga4c468e
- Cloud provider or hardware configuration: [AWS EKS](https://aws.amazon.com/eks/) (server version v1.31.3-eks-56e63d8), node instance type [g4dn.2xlarge](https://aws.amazon.com/ec2/instance-types/g4/)
- OS (e.g: `cat /etc/os-release`): [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2)
- Kernel (e.g. `uname -a`): 5.10.218
- Install tools: N/A
- Others: N/A

**Comment by ahg-g** [comment]
@Edwinhr716 we can address this bug as part of https://github.com/kubernetes-sigs/lws/pull/277; essentially the worker pod reconcile function should exit early if its current leader has a different revision hash key.

**Comment by xgchena** [comment]
Thanks for fixing the issue and looking forward to the new release.

**Comment by ahg-g** [comment]
> Thanks for fixing the issue and looking forward to the new release.

Released: https://github.com/kubernetes-sigs/lws/releases/tag/v0.5.0
