### ISSUE TITLE
Don't patch APIServer for each reconciliation

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#51]
**What would you like to be cleaned**:

For each reconciliation, we'll patch the APIServer, this is not necessary for only status updates.

**Why is this needed**:

Performance.

**Comment by liurupeng** [comment]
@kerthcet the reason why we are by default always perform patching for each reconciliation is that we don't need to detect if the lws object is updated. If the lws spec changed, without performing patching for each reconciliation, then we need to compare the current lws spec with the one we have to know that the object is updated. And this can only be done with controller revision support. We had a discuss with the sig-kernel folks,  the recommendation is to use server-side apply. I was worry about the performance, but I remembered seeing some document doing an analysis mentioning the influence is actually not high and expected. Somewhere around here: https://kubernetes.io/blog/2022/10/20/advanced-server-side-apply/

**Comment by bcfre** [comment]
@kerthcet Since we now already support ControllerRevision, will we change to performing actions based on whether the ControllerRevision has changed
