### ISSUE TITLE
Support rolling update in parallelism

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/lws#57]
**What would you like to be added**:

Based on the default design, rolling update will wait for the former replica ready, then we'll go process the next one, sometimes, for  stateless applications, this is unnecessary, this will accelerate the rolling update.

**Why is this needed**:

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by liurupeng** [comment]
`this is unnecessary, this will accelerate the rolling update.` do you plan to allow two kinds of upgrading mechanism? one is "waiting for the previous replica to be ready" and another one is "not waiting for the previous replica to be ready"?

**Comment by kerthcet** [comment]
Yeah, but i'm a little aggressive, we can set the maxUnavailable to achieve similar behavior, so close now. Sorry for the misdirection.
/close
