### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/lws#6]
We currently have unit and integration tests, we need to add end-to-end tests too that actually create a cluster and deploy lws.

See jobset example https://github.com/kubernetes-sigs/jobset/issues/46

**Comment by liurupeng** [comment]
@liurupeng

**Comment by kannon92** [comment]
Looks good now.
/close

Nice work @kerthcet, @Bslabe123 and @liurupeng
