### ISSUE TITLE
Allow setting  publishNotReadyAddresses=True when creating headless service

### ISSUE THREAD

**Issue by ahg-g** [kubernetes-sigs/lws#85]
**What would you like to be added**:

An option to set  `publishNotReadyAddresses=True` when creating the headless service of pod hostnames.

**Why is this needed**:

The headless service is used to simplify discovery of pod network IDs within a group for distributed computing, in most cases this is not related to any particular readiness status.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
Sorry still can't get the point, what's the `readiness status` refer to ?

**Comment by ahg-g** [comment]
The individual pods of each replica.

Recall that we create a headless service so that the individual pods get DNS records. By default this happens only when the pods are ready because DNS creates the records for the pods only when they get published in the EndpointSlice object, and by default EndpointSlice will publish them only when they are "ready".  We want to allow publishing those IPs from the get go.

**Comment by kerthcet** [comment]
Curiously, do you have any use case related with serving? The group pods need to communicate with each other before ready?

**Comment by ahg-g** [comment]
In general yes, in fact the group of pods need to communicate between each other to initialize the multi-host "replica" for the "replica" to be ready, right?

**Comment by kerthcet** [comment]
Make sense, maybe it should be the default behavior. But the negative impact is that the service will be exposed to the traffic before **Ready**, keep in mind that the large model usually takes longer to initialize. I saw people created two services to handle this, one for pod lookup, another for service.

/assign

**Comment by liurupeng** [comment]
@kerthcet we could make it as the default behavior, wdyt

**Comment by kerthcet** [comment]
Yes, you can work on this if you like, I haven't started yet.
/unassign
/assign @liurupeng

**Comment by kannon92** [comment]
@ahg-g do you think we should add a network field to the LWS spec? Like we have in Jobset.

I placed it there in Jobset but one could just implement this feature. I know that the one feature we have in Jobset that isn’t in network is forcing names for the service. Not sure if that is of interest to this group.
